name:  Start/Stop Service composite
description: Start/Stop Service composite
inputs:
    job_name:
      description: job Name
      required: true
      type: string

runs:
  using: "composite"
  steps:
    - name: Service test
      id: Service_test
      run: |
        echo "run the test1"
    - name: call the workflow
      uses: ./.github/workflows/call_in_action.yml
