name:  Start/Stop Service composite
description: Start/Stop Service composite
inputs:
    example_input:
      description: example input
      required: true
      type: string

runs:
  using: "composite"
  steps:
    - name: Service test
      id: Service_test
      shell: bash
      run: |
        echo "run the test1"
        echo "echo the inputs: ${{inputs.example_input}}"

    - name: call the workflow
      uses: ramnath2912/test/.github/workflows/call_in_action_helper.yml@main

