
name: call in action

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.generate.outputs.data }}
    steps:
      - name: Generate data
        id: generate
        run: |
          echo "Hello from Job 1" > data.txt
          echo "data=$(cat data.txt)" >> $GITHUB_OUTPUT

